### ISSUE TITLE
input error on ubuntu 22.04 with php 8.1.2

### ISSUE THREAD

**Issue by mjsduncan** [opencog/cogprotolab#4]
i'm a noob to network programing, so first question, do i have to use php 7.4.3?

i set up an alias in /etc/apache2/mods-available/alias.conf (copied from the "icons" alias as an example)
```
	Alias /cogprotolab/ "/home/mozi/oc/cogprotolab/cogprotolab/"

        <Directory "/home/mozi/oc/cogprotolab/cogprotolab">
                Options FollowSymlinks
                AllowOverride None
                Require all granted
        </Directory>
```
then i started a guile atomspace with the bioatomspace and started a cogserver for it
```
scheme@(guile-user)> (use-modules (opencog cogserver)) (start-cogserver)
;;; note: source file /usr/share/guile/site/3.0/opencog/cs-config.scm
;;;       newer than compiled /home/mozi/.cache/guile/ccache/3.0-LE-8-4.5/usr/share/guile/site/3.0/opencog/cs-config.scm.go
Listening on port 17001
$2 = "Started CogServer"
scheme@(guile-user)>
```
i can get telnet access through this:
```
 rlwrap telnet localhost 17001
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
scm
Entering scheme shell; use ^D or a single . on a line by itself to exit.
(count-all)
3483246
guile>
```
and going to _localhost/cogprotolab_ in the browser works, it shows the control and fractal pains, but when i put in a scheme line i get this:
```
(count-all)
<?php
    error_reporting(0);
    
    $host = urldecode($_POST['host']);
    $port = urldecode((int)$_POST['port']);
    $cmd = urldecode($_POST['cmd']);
    $prompt = str_replace("\\x1b", "", urldecode($_POST['prompt']));
    
    $fp = fsockopen($host, $port, $errno, $errstr, 5);

    if(!$fp){
        echo "telnet connection error: $errno $errstr";

    } else {
        //stream_set_blocking($fp, false);
        stream_set_timeout($fp, 0, 0);
        
        send($fp, $delay, "scm\n", $prompt);
        echo send($fp, $delay, "$cmd", $prompt);

        fclose($fp);
    }

    function send ($fp, $delay, $command, $prompt) {
        //write to socket
        if (fwrite($fp, $command) == false) {
            return "telnet command send error";
        }

        $response = "";
        //read socket
        while (true) {
            usleep(5000);
            while (($ret = fgets($fp)) != false) {
                if ($ret == $prompt) {
                    $response = substr($response, 0, -1);
                    return $response;
                }
                
                $response .= $ret;
            }
        }
    }
?>
```
i get the same error even if the shell telnet isn't running.  any idea what i'm doing wrong?

**Comment by contrast-zone** [comment]
`(count-all)` command works fine here.

It seems like php didn't process the command. Do you have any version of php installed? You can check that by typing `php -v` to linux command prompt window.

**Comment by mjsduncan** [comment]
ya it's 8.1.2, do i have to downgrade to 7.4.3 ?

**Comment by linas** [comment]
Hi Mike,

This part of your post looks wrong:
```
(count-all)
<?php
    error_reporting(0);
```

Let me explain why.  The first part `(count-all)` is valid only at the telnet prompt (and, as you point out, that worked fine for you.)  

The second part `<?php ...` is valid only in an html file.  So, for example, you'd edit `/home/mjsduncan/public_html/foobar.php` and put the `<?php stuff >` inside of it. Depending on your Apache configuration, the correct file  might also be `/var/www/foobar.php` You'd have to study the Apache conf file to get it.  

Anyway, after creating this file, you'd use you web browser and then open `http://127.0.0.1/~mjsduncan/foobar.php` for the first case, or maybe `http://127.0.0.1/foobar.php` for the second case (again, it depends..) 

When the web browser opens that URL, it causes the Apache server to run the php code. The php code then sends stuff to the cogserver, waits for an answer, and graphs the reply, gives it back to Apache, when then delivers it back to your browser, which draws it. 

Did that help?

**Comment by mjsduncan** [comment]
hi linus, i didn't enter the second part, that was returned after i entered the scheme line into the cogprotolab input box

**Comment by contrast-zone** [comment]
Could you try to run the thing without Apache alias? You would have to copy the `cogprotolab/` directory to your web server directory, usually in `/www/html/`, and access it over `localhost/cogprotolab/` from browser.

**Comment by linas** [comment]
> ya it's 8.1.2, do i have to downgrade to 7.4.3 ?

I'm 99% certain you don't need to.  Its something else.

> hi linus, i didn't enter the second part, that was returned after i entered the scheme line.

I don't understand... entered where? The cogserver can only return scheme (or python) so the cogserver will never return  `<?php stuff`  and the Apache server ... it umm, only talks the HTTP protocol. So I don't understand what you entered where.

**Comment by mjsduncan** [comment]
linus, i entered '(count-all)' into the cogprotolab web page and it returned the long string in http <?php....>

contrast-zone i get the same return string after copying the cogprotolab directory into '/var/www/http/'.

**Comment by linas** [comment]
>  i entered '(count-all)' into the cogprotolab web page

Ahh! OK, so ... here's the deal (you may not like it, but .. it is what it is... there is a way to fix it, and ... so let me explain...)

So @contrast-zone has this fractal visualizer,  it is designed for visualizing branching trees.  In version 1.0, he was visualizing outgoing sets of Links, which is OK, but kind-of boring, because most atoms in the atomspace are shallow -- trees only 2 or 3 levels deep.

So I have a collection of word-pair links, in the form `(ListLink (Word "foo") (Word "bar"))` which can be thought of as kind-of a tree, by chasing everything that "bar" is connected to, and then doing it again, and again.  To visualize this in the fractal visualizer, I had to cook up some snippets of scheme that would hop from one word to the next. It works, its in the git repo somewhere.

You've got gene and protein data, but it is not in the form of `(ListLink (Gene "foo") (Protein "bar"))`, its in a slightly different form.  To navigate this nicely, some snippet of scheme is needed to map it into the fractal-viewer API. The API is simple -- it just has "move left" and "move right" calls. I could write this snippet of code for you.  It's not "hard", it just needs some minor elbow grease. One of the iCogLabs people might be able to do it, I dunno. Or maybe I could create a rough draft, and someone else could polish it. 

Without this, your stuck visualizing just the outgoing set, which will be fairly boring. 

It's an open work item for @contrast-zone and I to sit down and hash out some kind of generic system that could work for "anyone" on "any" kind of dataset, but we've never gotten around to this. Your dataset is maybe the 2nd non-trivial dataset to be tried, so this will require ... some patience.

**Comment by linas** [comment]
So... @mjsduncan can you cut-n-paste a few dozen lines of "typical" gene-protein data, into this issue?  Then @contrast-zone the task is then bounce around from one gene to the next, one protein to the next, in this data structure. Its sort-of like the word-pair thing, but with genes and proteins. Count-all showed 3.5 million atoms, so, maybe half-a-million genes and proteins ....

**Comment by mjsduncan** [comment]
i see, i thought it was a generic atomspace explorer.  there are half a dozen inter-related data types, i'm using most of the files from here:  https://mozi.ai/datasets/current_2020-10-20/ 
which need the bioscience module from https://github.com/opencog/agi-bio.

i'll pull out some examples from each and post theme here for you

**Comment by contrast-zone** [comment]
3.5 million atoms is a bit of an overkill for cogprotolab.

Cogprotolab (using the version mentioned by Linas) is indeed a generic atomspace explorer, but currently your web server behaves like php isn't installed at all.

I propose, to test what is going on, to do one thing - write a small testing php script:

    <?php echo "test123"?>

and save it to `/var/www/html/test.php`. Now try to open this script in browser at `/localhost/test.php`. You should see the output `test123`. If you see anything else, then the problem is in php.

Please let us know how the test went, so we can consider further steps.

**Comment by contrast-zone** [comment]
@linas, just to check out, what is the last private mail you got from me? Did it end up in spam?

**Comment by mjsduncan** [comment]
you are correct, this produces a blank page, and viewing 'localhost/test1.php' gives a 404 error so i guess php isn't set up correctly.  it is installed:
```
$ php -v
PHP 8.1.2 (cli) (built: Apr  7 2022 17:46:26) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies
```

**Comment by contrast-zone** [comment]
Are you sure you got the testing filename right?

**Comment by mjsduncan** [comment]
```
$ cat /var/www/html/test.php
<?php echo "test123"?>
```
'http://localhost/test.php' in browser gives a blank white page 'http://localhost/test1.php' gives a 404 error

**Comment by contrast-zone** [comment]
Then yes, I suppose it's about your PHP installation malfunctioning. I really can't help you much with this one except advising to try to uninstall Apache and PHP and trying to install them again. I'm not particularly versed with Apache and PHP installing, but hopefully someone else could help you with that?

**Comment by linas** [comment]
>  PHP installation

@mjsduncan Review the apache config. There are two or three parts: one config file says "recognize .php suffix as requiring the php interpreter`, part two is configure `php_mod` to be available (I think that's what your very first post said?) and triple-check the `Allow` and `Require` setting to be should be. Look at `/var/log/apache2/whatever.log` for error messages.

I'll try to write shims for the genomic data, but might not get around to it for days or longer, nag me regularly. I don't mind nagging.

**Comment by linas** [comment]
> last private mail you got from me?

@contrast-zone I dunno, I am a month behind in unread emails.  I respond to most recent emails first, old ones can be rotting at the back of teh queue.

**Comment by mjsduncan** [comment]
changing test.php to
```
<?php echo '<p>test123</p>
```
prints out 'test123' in the browser window so php is working, it was just a syntax problem.

i then installed a compatibility checker and got this output, so i'm assuming code written for php 7.4 breaks in php 8.1
```
### php 8 compatibility check from
### https://haydenjames.io/php-8-compatibility-check-and-performance-tips/

## phan install & run

# ~/oc/cogprotolab$ sudo apt install composer
# ~/oc/cogprotolab$ composer require phan/phan
# ~/oc/cogprotolab/cogprotolab$ ../vendor/bin/phan --init --init-no-composer --init-level=3 --init-analyze-dir src
# ~/oc/cogprotolab/cogprotolab$ ../vendor/bin/phan --allow-polyfill-parser --project-root-directory . --progress-bar -o phan.out

## phan output

# ~/oc/cogprotolab/cogprotolab$cat phan.out

src/get-prompt.php:5 PhanTypeMismatchArgumentInternal Argument 1 ($string) is (int)($_GET['port']) of type int but \urldecode() takes string
src/get-prompt.php:7 PhanTypeMismatchArgumentInternal Argument 2 ($port) is $port of type string but \fsockopen() takes int
src/get-prompt.php:25 PhanRedefineFunction Function send defined at src/get-prompt.php:25 was previously defined at src/telnet.php:24
src/load-scripts.php:12 PhanTypeMismatchArgumentNullableInternal Argument 1 ($directory) is $dirstr of type ?'../scripts/scm/predefined'|?'../scripts/scm/visualization' but \scandir() takes string (expected type to be non-nullable)
src/save-scripts.php:12 PhanTypeMismatchArgumentNullableInternal Argument 1 ($directory) is $dirstr of type ?'../scripts/scm/predefined'|?'../scripts/scm/visualization' but \scandir() takes string (expected type to be non-nullable)
src/save-scripts.php:13 PhanTypeMismatchArgumentNullableInternal Argument 1 ($directory) is $dirstr of type ?'../scripts/scm/predefined'|?'../scripts/scm/visualization' but \chdir() takes string (expected type to be non-nullable)
src/save-scripts.php:24 PhanTypeArraySuspiciousNullable Suspicious array access to $allfiles of nullable type array|bool|float|int|null|string
src/telnet.php:5 PhanTypeMismatchArgumentInternal Argument 1 ($string) is (int)($_POST['port']) of type int but \urldecode() takes string
src/telnet.php:9 PhanTypeMismatchArgumentInternal Argument 2 ($port) is $port of type string but \fsockopen() takes int
src/telnet.php:24 PhanRedefineFunction Function send defined at src/telnet.php:24 was previously defined at src/get-prompt.php:25
```

here's a screenshot showing that the html layout is being rendered by the server:
![Screenshot from 2022-05-13 17-26-09](https://user-images.githubusercontent.com/5019970/168395531-e7ac4006-89b6-4c20-9117-a94176363609.png)

**Comment by contrast-zone** [comment]
The output you are seeing is actually the contents of `telnet.php` script. When `telnet.php` is called with the right parameters, it should return s-expr containing the contents of AtomSpace. I really don't have another explanation than that the script isn't even processed by php, like php intallation isn't there at all. If php would be working, and there would be errors in the script, the output would be empty because `error_reporting` is set to `0`.

I also assume `predefined script` and `visualization script` (calling `load-scripts.php` and `save-scripts.php`) white boxes of UI aren't populated because of the same problem.

**Comment by mjsduncan** [comment]
so you don't think this is due to differences in php syntax between version 7.4 and 8.1 ?

**Comment by contrast-zone** [comment]
I wouldn't certainly know, it may be. But did you try uninstall and install again Apache and PHP, and hopefully get rid of old config files? It should all work with defaults.

**Comment by mjsduncan** [comment]
turns out apache2 package for ubuntu 22.04 is configured for php 8.0 so once i switched it to 8.1 it works.

**Comment by linas** [comment]
@mjsduncan Heh. OK, that's solved. But ... to get a more interesting, meaningful display of your data, you still need shims to be created for this.  So I'm re-opening this, so that it serves as a reminder "create the visualizatino shims". Right?

**Comment by mjsduncan** [comment]
@linus i was going to start a new issue for that but putting it here is
fine.  i'm going through the scheme code for the snet gene annotation
service, which is made specifically to search the bio-ai hypergraph whose
files are linked above.
i don't have time to work on this for a few days but you may already be
familiar with the code from your optimization work:
https://github.com/MOZI-AI/annotation-scheme

**Comment by linas** [comment]
Yes, agreed, start a new issue. Reference this one for backstory.

OK, I know the data format. I guess I should assume it has not changed, and go with that.
